# This rule is not used by the project operators-entites itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to group.workloads.k8s.dodois.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: operators-entites
    app.kubernetes.io/managed-by: kustomize
  name: book-viewer-role
rules:
- apiGroups:
  - group.workloads.k8s.dodois.io
  resources:
  - books
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - group.workloads.k8s.dodois.io
  resources:
  - books/status
  verbs:
  - get
