# This rule is not used by the project operators-entites itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the group.workloads.k8s.dodois.io.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: operators-entites
    app.kubernetes.io/managed-by: kustomize
  name: book-editor-role
rules:
- apiGroups:
  - group.workloads.k8s.dodois.io
  resources:
  - books
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - group.workloads.k8s.dodois.io
  resources:
  - books/status
  verbs:
  - get
