# This rule is not used by the project operators-entites itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over group.workloads.k8s.dodois.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: operators-entites
    app.kubernetes.io/managed-by: kustomize
  name: book-admin-role
rules:
- apiGroups:
  - group.workloads.k8s.dodois.io
  resources:
  - books
  verbs:
  - '*'
- apiGroups:
  - group.workloads.k8s.dodois.io
  resources:
  - books/status
  verbs:
  - get
